version: '3'
services:
  docker:
    image: docker:dind
    privileged: yes
    volumes:
      - ${PWD}/certs/client:/certs/client
    networks:
      - pulumi-local-net

  pulumi:
    container_name: pulumi-local
    image: pulumi-local-${PROJECT_NAME}
    build:
      context: ${PWD}
      dockerfile: ${PWD}/Dockerfile
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_TLS_CERTDIR: /certs
      DOCKER_CERT_PATH: /certs/client
      PULUMI_CONFIG_PASSPHRASE_FILE: /passphrase.txt
      AWS_CONFIG_FILE: /.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /.aws/credentials
    volumes:
      - ${PWD}/certs/client:/certs/client/
      - ${PWD}/certs/registry.crt:/usr/local/share/ca-certificate/ca.crt
      - ${PWD}:/app
      - ${HOME}/.aws:/.aws
      - ${HOME}/.pulumi/passphrase.txt:/passphrase.txt
    working_dir: /app/
    networks:
      - pulumi-local-net
    depends_on:
      - docker

volumes:
  certs:

networks:
  pulumi-local-net:
    driver: bridge
